version: "3"

services:
  backend:
    build:
      context: backend
    container_name: init-build-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
  frontend:
    build:
      context: init-build-webcam-ai
    container_name: init-build-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NODE_PATH=./src
      - NEXT_TELEMETRY_DISABLED=1
